### ISSUE TITLE
Driver not found?

### ISSUE THREAD

**Issue by stefanofornari** [ing-bank/cassandra-jdbc-wrapper#30]
Hello, usually a JDBC driver is loaded from its URL and should not be specified. I am using ORMLite in my project and trying to use the cassandra jdbc I get this error:

```
 Caused by: java.lang.IllegalArgumentException: Unknown database-type url part 'cassandra' in: jdbc:cassandra://192.168.1.100:9042/keyspacetest?localdatacenter=DC1
        at com.j256.ormlite.jdbc.db.DatabaseTypeUtils.createDatabaseType(DatabaseTypeUtils.java:55)
        at com.j256.ormlite.jdbc.BaseJdbcConnectionSource.initialize(BaseJdbcConnectionSource.java:101)
        at com.j256.ormlite.jdbc.JdbcConnectionSource.<init>(JdbcConnectionSource.java:104)
        at com.j256.ormlite.jdbc.JdbcConnectionSource.<init>(JdbcConnectionSource.java:47)
```

Same thing if I use it in DBEaver without explicitly providing the driver.

Am I missing something?

**Comment by stefanofornari** [comment]
I am figuring it out ... it is an issue with ORMLite...
